### ISSUE TITLE
Connection with Firebase?

### ISSUE THREAD

**Issue by dandv** [lewislbr/lewis-gatsby-starter-blog#2]
I found this starter while searching for Firebase, but it doesn't appear to have much to do with Firebase. A stray keyword somewhere?

![image](https://user-images.githubusercontent.com/33569/66250720-bfcc3b00-e70b-11e9-817d-1f000c06cf1b.png)

**Comment by lewislbr** [comment]
Thanks for reporting this @dandv! Indeed, they have nothing to do with Firebase, it seems they only appear in the search because they have the demo link hosted with a `.firebaseapp.com` domain and get picked up by it.

**Comment by dandv** [comment]
Thanks for confirming. I've filed https://github.com/gatsbyjs/gatsby/issues/18223 for you.

**Comment by lewislbr** [comment]
Awesome, thanks!
