### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rahuldotbiz** [lewislbr/lewis-gatsby-starter-blog#6]
First of all thank you for creating such an awesome and amazing template. 

Can you add these 2 features plz
- Comment (disqus)
- Mailchimp (subscribe)

I'm in love with this template.

**Comment by lewislbr** [comment]
Hi @rahxuls, thank you for your kind words! I created this template to use as a starting point to build a personalized blog, so I didn't added extra features that are very dependent on the use case. However, feel free to extend from here however you would like! I'm sure there will be great tutorials explaining how to achieve it easily. 

All the best 🙌
